#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Portfolio Backtest Framework with Analysis

基于 portfolio_analysis 函数的通用回测框架
支持日频、周频、月频等不同频率的回测
支持自定义策略和基准对比

Author: Generated by AI Assistant
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple, Callable
import warnings
warnings.filterwarnings('ignore')

# 设置中文字体
plt.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']
plt.rcParams['axes.unicode_minus'] = False

def portfolio_analysis(df, freq, additional_columns=[]):
    """
    计算投资组合分析指标，包括年化收益、年化标准差、信息比率、最大回撤、VaR、CVaR 和命中率 (hit ratio)。

    参数：
    - df: pd.DataFrame, 包含投资组合收益数据
    - freq: int, 年化频率 (如月度为 12，日度为 252)
    - additional_columns: list, 额外包含的列（如 'next_stock'、'next_bond'）

    返回：
    - result_df: pd.DataFrame, 投资组合分析结果
    """
    selected_columns = additional_columns
    df = df[selected_columns].dropna()

    # 计算累计收益
    cumulative_returns = (df + 1).cumprod()
    portfolio_cumprod = cumulative_returns.iloc[-1]

    # 计算最大回撤
    rollmax = cumulative_returns.rolling(len(df), min_periods=1).max()
    portfolio_drawdown = (cumulative_returns - rollmax) / rollmax
    max_drawdown = portfolio_drawdown.min()

    # 计算标准差
    std = df.std()
    annual_std = std * np.sqrt(freq)

    # 计算年化收益
    length = len(df) / freq
    annual_return = portfolio_cumprod ** (1 / length) - 1

    # 计算信息比率
    ir = annual_return / annual_std

    # 计算 VaR 和 CVaR
    var = df.apply(lambda x: np.percentile(x.dropna(), 5))
    cvar = df.apply(lambda x: x[x < np.percentile(x.dropna(), 5)].mean())

    # 计算命中率 (hit ratio)
    hit_ratio = df.apply(lambda x: len(x[x > 0]) / len(x))

    # 生成结果表
    result_df = pd.DataFrame({
        'Annualized Return': annual_return * 100,
        'Annualized Standard Deviation': annual_std * 100,
        'Information Ratio': ir,
        'Max Drawdown': max_drawdown * 100,
        'VaR': var * 100,
        'CVaR': cvar * 100,
        'Hit Ratio': hit_ratio
    })

    return result_df.round(2)


class PortfolioBacktest:
    """
    投资组合回测框架
    """
    
    def __init__(self, 
                 initial_capital: float = 1000000,
                 commission_rate: float = 0.0003,
                 slippage: float = 0.001,
                 rebalance_freq: str = 'weekly',
                 benchmark_data: Optional[pd.DataFrame] = None):
        """
        初始化回测框架
        
        参数：
        - initial_capital: 初始资金
        - commission_rate: 手续费率
        - slippage: 滑点
        - rebalance_freq: 调仓频率 ('daily', 'weekly', 'monthly')
        - benchmark_data: 基准数据
        """
        self.initial_capital = initial_capital
        self.commission_rate = commission_rate
        self.slippage = slippage
        self.rebalance_freq = rebalance_freq
        
        # 回测结果
        self.positions = {}  # 当前持仓
        self.cash = initial_capital
        self.equity_curve = []
        self.trades = []
        self.returns = []
        
        # 基准数据
        self.benchmark_data = benchmark_data
        self.benchmark_returns = []
        
        # 频率映射
        self.freq_map = {
            'daily': 252,
            'weekly': 52,
            'monthly': 12
        }
        
    def set_strategy(self, strategy_func: Callable):
        """
        设置策略函数
        
        参数：
        - strategy_func: 策略函数，接收当前数据和持仓，返回目标权重
        """
        self.strategy_func = strategy_func
        
    def run_backtest(self, 
                    price_data: pd.DataFrame,
                    start_date: Optional[str] = None,
                    end_date: Optional[str] = None) -> pd.DataFrame:
        """
        运行回测
        
        参数：
        - price_data: 价格数据，包含日期索引和股票代码列
        - start_date: 开始日期
        - end_date: 结束日期
        
        返回：
        - 回测结果DataFrame
        """
        # 数据预处理
        if start_date:
            price_data = price_data[price_data.index >= start_date]
        if end_date:
            price_data = price_data[price_data.index <= end_date]
            
        # 计算收益率
        returns_data = price_data.pct_change().dropna()
        
        # 确定调仓日期
        rebalance_dates = self._get_rebalance_dates(returns_data.index)
        
        print(f"开始回测: {returns_data.index[0].date()} 到 {returns_data.index[-1].date()}")
        print(f"调仓频率: {self.rebalance_freq}, 总调仓次数: {len(rebalance_dates)}")
        
        # 初始化
        self.positions = {}
        self.cash = self.initial_capital
        self.equity_curve = []
        self.trades = []
        self.returns = []
        self._prev_total_value = None   # <<< 关键：每次回测前重置
        
        # 主回测循环
        for i, date in enumerate(returns_data.index):
            current_prices = price_data.loc[date]
            
            # 调仓日执行策略
            if date in rebalance_dates:
                target_weights = self.strategy_func(price_data, self.positions, date)
                self._rebalance_portfolio(target_weights, current_prices, date)
            
            # 计算当日收益
            daily_return = self._calculate_daily_return(current_prices)
            self.returns.append(daily_return)
            
            # 更新净值
            self._update_equity(date, daily_return, current_prices)
            
            # 更新基准收益
            if self.benchmark_data is not None and date in self.benchmark_data.index:
                self.benchmark_returns.append(self.benchmark_data.loc[date])
            else:
                self.benchmark_returns.append(0.0)
        
        # 生成回测结果
        return self._generate_results(returns_data.index)
    
    def _get_rebalance_dates(self, dates: pd.DatetimeIndex) -> List[pd.Timestamp]:
        """获取调仓日期"""
        if self.rebalance_freq == 'daily':
            return list(dates)
        elif self.rebalance_freq == 'weekly':
            # 每周最后一个交易日 ✅
            weekly_dates = []
            current_week = dates[0].isocalendar()[1]
            last_date = dates[0]
            for d in dates[1:]:
                wk = d.isocalendar()[1]
                if wk != current_week:
                    weekly_dates.append(last_date)  # 上一周的最后一天
                    current_week = wk
                last_date = d
            weekly_dates.append(dates[-1])  # 别漏掉最后一周
            return weekly_dates
        elif self.rebalance_freq == 'monthly':
            # 每月最后一个交易日
            monthly_dates = []
            current_month = None
            for date in dates:
                if current_month != date.month:
                    current_month = date.month
                    monthly_dates.append(date)
            return monthly_dates
        else:
            return list(dates)
    
    def _rebalance_portfolio(self, target_weights: Dict, current_prices: pd.Series, date: pd.Timestamp):
        """调仓"""
        # 用"持仓市值 + 现金"作为可投资基数 ✅
        total_value = self._get_portfolio_value(current_prices) + self.cash
        target_positions = {}
        
        for asset, weight in target_weights.items():
            if asset in current_prices.index:
                target_value = total_value * weight
                target_shares = int(target_value / current_prices[asset])
                if target_shares > 0:
                    target_positions[asset] = target_shares
        
        # 执行交易
        self._execute_trades(target_positions, current_prices, date)
    
    def _execute_trades(self, target_positions: Dict, current_prices: pd.Series, date: pd.Timestamp):
        """执行交易"""
        # 卖出不需要的持仓
        for asset, current_shares in self.positions.items():
            if asset not in target_positions or target_positions[asset] < current_shares:
                shares_to_sell = current_shares - target_positions.get(asset, 0)
                if shares_to_sell > 0:
                    sell_value = shares_to_sell * current_prices[asset]
                    sell_value_net = sell_value * (1 - self.commission_rate - self.slippage)
                    self.cash += sell_value_net
                    
                    # 记录交易
                    self.trades.append({
                        'date': date,
                        'asset': asset,
                        'action': 'SELL',
                        'shares': shares_to_sell,
                        'price': current_prices[asset],
                        'value': sell_value_net
                    })
        
        # 买入需要的持仓
        for asset, target_shares in target_positions.items():
            current_shares = self.positions.get(asset, 0)
            if target_shares > current_shares:
                shares_to_buy = target_shares - current_shares
                buy_value = shares_to_buy * current_prices[asset]
                buy_value_net = buy_value * (1 + self.commission_rate + self.slippage)
                
                if buy_value_net <= self.cash:
                    self.cash -= buy_value_net
                    self.positions[asset] = target_shares
                    
                    # 记录交易
                    self.trades.append({
                        'date': date,
                        'asset': asset,
                        'action': 'BUY',
                        'shares': shares_to_buy,
                        'price': current_prices[asset],
                        'value': buy_value_net
                    })
        
        # 更新持仓
        self.positions = {k: v for k, v in target_positions.items() if v > 0}
    
    def _calculate_daily_return(self, current_prices: pd.Series) -> float:
        """计算当日收益"""
        portfolio_value = self._get_portfolio_value(current_prices)
        total_value = portfolio_value + self.cash
        
        if hasattr(self, '_prev_total_value') and self._prev_total_value is not None and self._prev_total_value > 0:
            daily_return = (total_value / self._prev_total_value) - 1
        else:
            daily_return = 0.0
            
        self._prev_total_value = total_value
        return daily_return
    
    def _get_portfolio_value(self, current_prices: pd.Series) -> float:
        """获取组合市值"""
        portfolio_value = 0.0
        for asset, shares in self.positions.items():
            if asset in current_prices.index:
                portfolio_value += shares * current_prices[asset]
        return portfolio_value
    
    def _update_equity(self, date: pd.Timestamp, daily_return: float, current_prices: pd.Series):
        """更新净值曲线（用真实价格估值）"""
        total_value = self._get_portfolio_value(current_prices) + self.cash
        
        self.equity_curve.append({
            'date': date,
            'equity': total_value,
            'return': daily_return,
            'cash': self.cash,
            'positions': len(self.positions)
        })
    
    def _generate_results(self, dates: pd.DatetimeIndex) -> pd.DataFrame:
        """生成回测结果"""
        # 创建结果DataFrame
        results_df = pd.DataFrame(self.equity_curve)
        results_df.set_index('date', inplace=True)
        
        # 计算累计收益
        results_df['cumulative_return'] = (1 + results_df['return']).cumprod() - 1
        
        # 计算基准收益
        if self.benchmark_data is not None:
            benchmark_df = pd.DataFrame({
                'date': dates,
                'benchmark_return': self.benchmark_returns
            }).set_index('date')
            results_df = results_df.join(benchmark_df)
            results_df['benchmark_cumulative'] = (1 + results_df['benchmark_return']).cumprod() - 1
        
        return results_df
    
    def analyze_performance(self, results_df: pd.DataFrame) -> pd.DataFrame:
        """分析回测表现"""
        freq = self.freq_map.get(self.rebalance_freq, 252)
        
        # 策略表现分析
        strategy_returns = results_df[['return']].copy()
        strategy_returns.columns = ['strategy_return']
        
        strategy_analysis = portfolio_analysis(
            df=strategy_returns, 
            freq=freq, 
            additional_columns=['strategy_return']
        )
        
        # 基准表现分析（如果有）
        if 'benchmark_return' in results_df.columns:
            benchmark_returns = results_df[['benchmark_return']].copy()
            benchmark_returns.columns = ['benchmark_return']
            
            benchmark_analysis = portfolio_analysis(
                df=benchmark_returns, 
                freq=freq, 
                additional_columns=['benchmark_return']
            )
            
            # 合并结果
            combined_analysis = pd.concat([
                strategy_analysis.rename(index={'strategy_return': 'Strategy'}),
                benchmark_analysis.rename(index={'benchmark_return': 'Benchmark'})
            ])
            
            return combined_analysis
        
        return strategy_analysis
    
    def plot_results(self, results_df: pd.DataFrame, save_path: Optional[str] = None):
        """绘制回测结果"""
        fig, axes = plt.subplots(2, 2, figsize=(15, 10))
        fig.suptitle(f'Portfolio Backtest Results ({self.rebalance_freq})', fontsize=16)
        
        # 1. 净值曲线
        ax1 = axes[0, 0]
        ax1.plot(results_df.index, results_df['equity'], label='Portfolio', linewidth=2)
        if 'benchmark_cumulative' in results_df.columns:
            ax1.plot(results_df.index, 
                    results_df['benchmark_cumulative'] * self.initial_capital + self.initial_capital, 
                    label='Benchmark', linewidth=2, alpha=0.7)
        ax1.set_title('Portfolio Value')
        ax1.set_ylabel('Value')
        ax1.legend()
        ax1.grid(True, alpha=0.3)
        
        # 2. 累计收益
        ax2 = axes[0, 1]
        ax2.plot(results_df.index, results_df['cumulative_return'] * 100, label='Portfolio', linewidth=2)
        if 'benchmark_cumulative' in results_df.columns:
            ax2.plot(results_df.index, results_df['benchmark_cumulative'] * 100, 
                    label='Benchmark', linewidth=2, alpha=0.7)
        ax2.set_title('Cumulative Returns (%)')
        ax2.set_ylabel('Return (%)')
        ax2.legend()
        ax2.grid(True, alpha=0.3)
        
        # 3. 回撤
        ax3 = axes[1, 0]
        cumulative = (1 + results_df['return']).cumprod()
        running_max = cumulative.expanding().max()
        drawdown = (cumulative - running_max) / running_max * 100
        ax3.fill_between(results_df.index, drawdown, 0, alpha=0.3, color='red')
        ax3.plot(results_df.index, drawdown, color='red', linewidth=1)
        ax3.set_title('Drawdown (%)')
        ax3.set_ylabel('Drawdown (%)')
        ax3.grid(True, alpha=0.3)
        
        # 4. 持仓数量
        ax4 = axes[1, 1]
        ax4.plot(results_df.index, results_df['positions'], linewidth=2)
        ax4.set_title('Number of Positions')
        ax4.set_ylabel('Count')
        ax4.grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
        plt.show()
        
        return fig
        
        return fig


# ========= 示例策略函数 =========

def equal_weight_strategy(price_data: pd.DataFrame, 
                         current_positions: Dict, 
                         current_date: pd.Timestamp) -> Dict:
    """
    等权重策略示例
    
    参数：
    - price_data: 价格数据，包含日期索引和股票代码列
    - current_positions: 当前持仓
    - current_date: 当前日期
    
    返回：
    - 目标权重字典
    """
    # 获取当前可交易的资产（基于价格数据的列名）
    available_assets = price_data.columns.tolist()
    
    if not available_assets:
        return {}
    
    # 等权重分配
    n_assets = len(available_assets)
    weight_per_asset = 1.0 / n_assets
    
    target_weights = {asset: weight_per_asset for asset in available_assets}
    
    return target_weights


def momentum_strategy(price_data: pd.DataFrame, 
                     current_positions: Dict, 
                     current_date: pd.Timestamp,
                     lookback_period: int = 20,
                     top_n: int = 10) -> Dict:
    """
    动量策略示例
    
    参数：
    - price_data: 价格数据，包含日期索引和股票代码列
    - current_positions: 当前持仓
    - current_date: 当前日期
    - lookback_period: 回看期
    - top_n: 选择前N个资产
    
    返回：
    - 目标权重字典
    """
    if len(price_data) < lookback_period:
        return {}
    
    # 计算动量（过去N期累计收益）
    lookback_prices = price_data.iloc[-lookback_period:]
    cumulative_returns = (lookback_prices.iloc[-1] / lookback_prices.iloc[0]) - 1
    
    # 选择动量最强的top_n个资产
    top_assets = cumulative_returns.nlargest(top_n).index.tolist()
    
    if not top_assets:
        return {}
    
    # 等权重分配
    weight_per_asset = 1.0 / len(top_assets)
    target_weights = {asset: weight_per_asset for asset in top_assets}
    
    return target_weights


def mean_reversion_strategy(price_data: pd.DataFrame, 
                           current_positions: Dict, 
                           current_date: pd.Timestamp,
                           lookback_period: int = 20,
                           top_n: int = 10) -> Dict:
    """
    均值回归策略示例
    
    参数：
    - price_data: 价格数据，包含日期索引和股票代码列
    - current_positions: 当前持仓
    - current_date: 当前日期
    - lookback_period: 回看期
    - top_n: 选择前N个资产
    
    返回：
    - 目标权重字典
    """
    if len(price_data) < lookback_period:
        return {}
    
    # 计算过去N期的平均收益
    lookback_prices = price_data.iloc[-lookback_period:]
    mean_returns = (lookback_prices.iloc[-1] / lookback_prices.iloc[0]) - 1
    
    # 选择平均收益最低的top_n个资产（均值回归）
    bottom_assets = mean_returns.nsmallest(top_n).index.tolist()
    
    if not bottom_assets:
        return {}
    
    # 等权重分配
    weight_per_asset = 1.0 / len(bottom_assets)
    target_weights = {asset: weight_per_asset for asset in bottom_assets}
    
    return target_weights


# ========= 主函数示例 =========

def main():
    """主函数示例"""
    print("=== Portfolio Backtest Framework Demo ===\n")
    
    # 1. 生成模拟数据
    print("1. 生成模拟数据...")
    np.random.seed(42)
    
    # 生成100个交易日，20个资产的价格数据
    dates = pd.date_range('2023-01-01', periods=100, freq='D')
    n_assets = 20
    asset_names = [f'Asset_{i:02d}' for i in range(n_assets)]
    
    # 生成价格数据（随机游走）
    price_data = pd.DataFrame(index=dates, columns=asset_names)
    for asset in asset_names:
        returns = np.random.normal(0.001, 0.02, len(dates))  # 日收益0.1%，波动率2%
        prices = 100 * (1 + returns).cumprod()
        price_data[asset] = prices
    
    print(f"数据形状: {price_data.shape}")
    print(f"数据范围: {price_data.index[0].date()} 到 {price_data.index[-1].date()}")
    
    # 2. 创建回测框架
    print("\n2. 创建回测框架...")
    backtest = PortfolioBacktest(
        initial_capital=1000000,
        commission_rate=0.0003,
        slippage=0.001,
        rebalance_freq='weekly'
    )
    
    # 3. 运行等权重策略回测
    print("\n3. 运行等权重策略回测...")
    backtest.set_strategy(equal_weight_strategy)
    results_equal = backtest.run_backtest(price_data)
    
    # 快速冒烟测试
    print(f"交易笔数: {len(backtest.trades)}")
    print(results_equal[['equity','positions']].head())
    
    # 4. 分析表现
    print("\n4. 分析策略表现...")
    analysis_equal = backtest.analyze_performance(results_equal)
    print("等权重策略表现:")
    print(analysis_equal)
    
    # 5. 运行动量策略回测
    print("\n5. 运行动量策略回测...")
    backtest.set_strategy(lambda p, pos, d: momentum_strategy(p, pos, d, lookback_period=20, top_n=5))
    results_momentum = backtest.run_backtest(price_data)
    
    analysis_momentum = backtest.analyze_performance(results_momentum)
    print("\n动量策略表现:")
    print(analysis_momentum)
    
    # 6. 运行均值回归策略回测
    print("\n6. 运行均值回归策略回测...")
    backtest.set_strategy(lambda p, pos, d: mean_reversion_strategy(p, pos, d, lookback_period=20, top_n=5))
    results_reversion = backtest.run_backtest(price_data)
    
    analysis_reversion = backtest.analyze_performance(results_reversion)
    print("\n均值回归策略表现:")
    print(analysis_reversion)
    
    # 7. 绘制结果
    print("\n7. 绘制回测结果...")
    backtest.set_strategy(equal_weight_strategy)
    results_final = backtest.run_backtest(price_data)
    backtest.plot_results(results_final, save_path='backtest_results.png')
    
    # 8. 保存结果
    print("\n8. 保存结果...")
    results_final.to_csv('backtest_results.csv')
    
    # 汇总所有策略表现
    print("\n=== 策略表现汇总 ===")
    summary_data = []
    
    # 等权重
    backtest.set_strategy(equal_weight_strategy)
    results = backtest.run_backtest(price_data)
    analysis = backtest.analyze_performance(results)
    summary_data.append(analysis.iloc[0].to_dict())
    
    # 动量
    backtest.set_strategy(lambda p, pos, d: momentum_strategy(p, pos, d, lookback_period=20, top_n=5))
    results = backtest.run_backtest(price_data)
    analysis = backtest.analyze_performance(results)
    summary_data.append(analysis.iloc[0].to_dict())
    
    # 均值回归
    backtest.set_strategy(lambda p, pos, d: mean_reversion_strategy(p, pos, d, lookback_period=20, top_n=5))
    results = backtest.run_backtest(price_data)
    analysis = backtest.analyze_performance(results)
    summary_data.append(analysis.iloc[0].to_dict())
    
    summary_df = pd.DataFrame(summary_data, 
                             index=['Equal Weight', 'Momentum', 'Mean Reversion'])
    print(summary_df)
    
    print("\n回测完成！结果已保存到 backtest_results.csv 和 backtest_results.png")


if __name__ == "__main__":
    main()
